name: flutter_skill_test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.3
  icons_launcher: ^3.0.0
  flutter_svg: ^2.0.16
  rename_app: ^1.6.1
  connectivity_plus: ^6.1.1
  dartz: ^0.10.1
  http: ^1.2.2
  shimmer: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  fluttertoast: ^8.2.10
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/houses/
    - assets/icons/
    - assets/json/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

icons_launcher:
  image_path: "assets/logo/ird.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true